# Generated by Django 3.1.6 on 2021-02-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_restaurant',
            field=models.BooleanField(default=True),
        ),
    ]
