# Generated by Django 3.1.6 on 2021-02-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooditem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='food_image'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
