# Generated by Django 3.1.6 on 2021-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210304_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Served', 'Order is Served'), ('Cooking', 'Order is Cooking')], default='Cooking', max_length=30),
        ),
    ]
